### ISSUE TITLE
Error getting started

### ISSUE THREAD

**Issue by odinian** [justinclarkhome/AlphaVantageStockDB#2]
Hi. I'm looking forward to using your code, but I hit a snag just getting started.

creds.yaml is set up.

Any ideas?

$ python3 updater.py  --daily --intraday
2019-12-26 12:42:51,733 - INFO - USING DATABASE: PRICES_DAILY
Traceback (most recent call last):
  File "updater.py", line 548, in <module>
    db_info, data_source_info = parse_creds(cred_file, database_name=database_name)
  File "updater.py", line 517, in parse_creds
    data = yaml.load(f, Loader=yaml.FullLoader)
AttributeError: module 'yaml' has no attribute 'FullLoader'

**Comment by justinclarkhome** [comment]
Hi - I'm so sorry I took me so long to respond here! I don't think I ever saw a notification and I haven't logged in in a while.

Maybe this?

https://stackoverflow.com/questions/55551191/module-yaml-has-no-attribute-fullloader

FWIW, code is still running ok on my machine (I use Anaconda and update regularly).
