### ISSUE TITLE
change "SecurityMetadata" to "SecurityMetaData"

### ISSUE THREAD

**Issue by lidutech** [justinclarkhome/AlphaVantageStockDB#3]
In updater.py Line 488:

answer = fetchone(sql_cursor, query="SELECT SecurityMetaDataID FROM **SecurityMetadata** WHERE SecuritySymbol='{}'".format(symbol))

You should change "SecurityMetadata" to "SecurityMetaData"

**Comment by justinclarkhome** [comment]
That is done - good catch! Thanks.
